/**
 * Claim generator
 *
 * Assembles an evidence-backed, vendor-ready claim email from the measured
 * uptime report, the applicable SLA tier, and the incident list.
 *
 * The email is written in the tone successful credit recovery teams use —
 * firm, precise, no emotion. We always:
 *   • Reference the exact SLA clause
 *   • Attach an evidence block (timestamps, durations, status codes)
 *   • State the computed credit in dollars AND as % of monthly fees
 *   • Provide a polite-but-clear response deadline
 */

import type { BreachResult, UptimeReport } from '@/lib/sla/engine';
import { formatCents, formatDuration, formatUptime } from '@/lib/sla/engine';

export interface GenerateClaimInput {
  vendor: {
    name: string;
    contactEmail?: string | null;
    monthlySpendCents: number;
  };
  period: string;
  uptime: UptimeReport;
  breach: BreachResult;
  customer: {
    orgName: string;
    userName: string;
    userEmail: string;
  };
  sourceExcerpt?: string | null;
}

export interface GeneratedClaim {
  subject: string;
  body: string;
  evidence: {
    period: string;
    uptimePct: number;
    downtimeSeconds: number;
    incidentCount: number;
    tier: { threshold: number | null; creditPct: number };
    incidents: Array<{
      startedAt: number;
      endedAt: number | null;
      durationSeconds: number | null;
      severity: 'minor' | 'major' | 'critical';
      summary: string;
    }>;
  };
}

function formatHumanDate(seconds: number): string {
  return new Date(seconds * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}

export function generateClaim(input: GenerateClaimInput): GeneratedClaim {
  const { vendor, period, uptime, breach, customer, sourceExcerpt } = input;
  const creditAmount = formatCents(breach.estimatedCreditCents);
  const evidenceBlock = uptime.incidents
    .slice(0, 20)
    .map((inc, i) => {
      const start = formatHumanDate(inc.startedAt);
      const end = inc.endedAt ? formatHumanDate(inc.endedAt) : 'ongoing';
      const dur = inc.durationSeconds
        ? formatDuration(inc.durationSeconds)
        : 'ongoing';
      return `${i + 1}. ${start} → ${end} · ${dur} · ${inc.severity.toUpperCase()} · ${inc.summary}`;
    })
    .join('\n');

  const subject = `Service Credit Claim · ${vendor.name} · ${period} · ${creditAmount}`;

  const body = `Hello ${vendor.name} Support Team,

I'm writing on behalf of ${customer.orgName} to formally request a service credit under the SLA for the ${period} billing period.

Our independent monitoring shows measured uptime of ${formatUptime(uptime.uptimePct)} during this period, which falls below the ${breach.threshold}% SLA threshold. Per our agreement, this entitles us to a ${breach.creditPct}% credit against our monthly fees.

────────────────────────────────────────────────
MEASUREMENT SUMMARY
  Period                ${period}
  Measured uptime       ${formatUptime(uptime.uptimePct)}
  SLA threshold         ${breach.threshold}%
  Total downtime        ${formatDuration(uptime.downtimeSeconds)} across ${uptime.incidentCount} incident${uptime.incidentCount === 1 ? '' : 's'}
  Applicable credit     ${breach.creditPct}% of monthly fees
  Monthly fees          ${formatCents(vendor.monthlySpendCents)}
  Requested credit      ${creditAmount}

INCIDENT LOG (UTC)
${evidenceBlock || '  (no incidents recorded)'}

${sourceExcerpt ? `SLA CLAUSE REFERENCED\n  "${sourceExcerpt.trim()}"\n` : ''}────────────────────────────────────────────────

Please confirm receipt within 5 business days and let us know the process and timeline for issuing the credit. Happy to provide any additional documentation required.

Thank you,

${customer.userName}
${customer.orgName}
${customer.userEmail}

— Generated by ClaimRail · https://claimrail.io
`;

  return {
    subject,
    body,
    evidence: {
      period,
      uptimePct: uptime.uptimePct,
      downtimeSeconds: uptime.downtimeSeconds,
      incidentCount: uptime.incidentCount,
      tier: { threshold: breach.threshold, creditPct: breach.creditPct },
      incidents: uptime.incidents.map((i) => ({
        startedAt: i.startedAt,
        endedAt: i.endedAt,
        durationSeconds: i.durationSeconds,
        severity: i.severity,
        summary: i.summary,
      })),
    },
  };
}
